

const logo =
  "https://cdn.pixabay.com/photo/2015/12/11/11/43/google-1088004_1280.png";
const locationIcon =
  "https://th.bing.com/th/id/OIP.uaE0b1zWCSltX4oXX-HFEAHaJk?rs=1&pid=ImgDetMain";
const savedIcon =
  "https://cdn2.iconfinder.com/data/icons/electronic-line-3/64/Bookmark_favourite_pin_saved_interface_icon-512.png";
export const data = [
  {
    title: "Technical Support Specialist",
    remote: "REMOTE",
    salary: "$20,000 - $25,000",
    companyName: "Google Inc.",
    companyLogo: logo,
    location: "Dhaka, Bangladesh",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Senior UX Designer",
    remote: "REMOTE",
    salary: "$20,000 - $25,000",
    companyName: "Google Inc.",
    companyLogo: logo,
    location: "San Francisco, USA",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Marketing Manager",
    remote: "ONSITE",
    salary: "$30,000 - $40,000",
    companyName: "Apple Inc.",
    companyLogo: logo,
    location: "London, UK",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Front End Developer",
    remote: "REMOTE",
    salary: "$25,000 - $35,000",
    companyName: "Microsoft",
    companyLogo: logo,
    location: "Berlin, Germany",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Product Designer",
    remote: "HYBRID",
    salary: "$20,000 - $28,000",
    companyName: "Amazon",
    companyLogo: logo,
    location: "Toronto, Canada",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Junior Graphic Designer",
    remote: "ONSITE",
    salary: "$15,000 - $20,000",
    companyName: "Adobe",
    companyLogo: logo,
    location: "Sydney, Australia",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Software Engineer",
    remote: "REMOTE",
    salary: "$40,000 - $50,000",
    companyName: "Netflix",
    companyLogo: logo,
    location: "Paris, France",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Data Scientist",
    remote: "REMOTE",
    salary: "$50,000 - $60,000",
    companyName: "Facebook",
    companyLogo: logo,
    location: "New York, USA",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Interaction Designer",
    remote: "ONSITE",
    salary: "$22,000 - $30,000",
    companyName: "Spotify",
    companyLogo: logo,
    location: "Stockholm, Sweden",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Visual Designer",
    remote: "REMOTE",
    salary: "$18,000 - $22,000",
    companyName: "Canva",
    companyLogo: logo,
    location: "Bangkok, Thailand",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Network Engineer",
    remote: "HYBRID",
    salary: "$35,000 - $45,000",
    companyName: "Cisco",
    companyLogo: logo,
    location: "Singapore, Singapore",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "DevOps Engineer",
    remote: "REMOTE",
    salary: "$50,000 - $70,000",
    companyName: "IBM",
    companyLogo: logo,
    location: "Dubai, UAE",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Machine Learning Engineer",
    remote: "ONSITE",
    salary: "$60,000 - $80,000",
    companyName: "Google Inc.",
    companyLogo: logo,
    location: "Zurich, Switzerland",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Content Strategist",
    remote: "REMOTE",
    salary: "$25,000 - $30,000",
    companyName: "Medium",
    companyLogo: logo,
    location: "Los Angeles, USA",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Game Developer",
    remote: "ONSITE",
    salary: "$40,000 - $60,000",
    companyName: "Unity",
    companyLogo: logo,
    location: "Tokyo, Japan",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "AI Researcher",
    remote: "HYBRID",
    salary: "$70,000 - $90,000",
    companyName: "OpenAI",
    companyLogo: logo,
    location: "Boston, USA",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Cybersecurity Analyst",
    remote: "ONSITE",
    salary: "$50,000 - $65,000",
    companyName: "CrowdStrike",
    companyLogo: logo,
    location: "Mumbai, India",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Digital Marketing Specialist",
    remote: "REMOTE",
    salary: "$20,000 - $25,000",
    companyName: "HubSpot",
    companyLogo: logo,
    location: "Cape Town, South Africa",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Full Stack Developer",
    remote: "HYBRID",
    salary: "$40,000 - $55,000",
    companyName: "Twitter",
    companyLogo: logo,
    location: "Madrid, Spain",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Backend Developer",
    remote: "REMOTE",
    salary: "$35,000 - $45,000",
    companyName: "Dropbox",
    companyLogo: logo,
    location: "Rome, Italy",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "IT Consultant",
    remote: "ONSITE",
    salary: "$50,000 - $70,000",
    companyName: "Deloitte",
    companyLogo: logo,
    location: "Toronto, Canada",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Cloud Architect",
    remote: "REMOTE",
    salary: "$70,000 - $90,000",
    companyName: "AWS",
    companyLogo: logo,
    location: "San Jose, USA",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "Business Analyst",
    remote: "ONSITE",
    salary: "$40,000 - $55,000",
    companyName: "Accenture",
    companyLogo: logo,
    location: "Kuala Lumpur, Malaysia",
    loc: locationIcon,
    saved: savedIcon,
  },
  {
    title: "SEO Specialist",
    remote: "REMOTE",
    salary: "$25,000 - $35,000",
    companyName: "Moz",
    companyLogo: logo,
    location: "Bangkok, Thailand",
    loc: locationIcon,
    saved: savedIcon,
  },
];
